version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-slim
        auth:
          username: mydockerusername
          password: dockerhubpassword
    working_directory: ~/webapp

    steps:
      - checkout

      - run: mvn clean package